
# poziom pierwszy
p1_zwierzeta = [[["Które z tych zwierząt jest tradycyjnie nazywane najlepszym przyjacielem człowieka?"],["A) Kot","B) Chomik","C) Pies","D) Papuga"],["C"]], [["Które z tych zwierząt nie występuje naturalnie w Afryce?"], ["A) Lew", "B) Panda Wielka", "C) Zebra", "D) Żyrafa"], ["B"]], [["Jaki ptak znajduje się na polskim godle?"], ["A) Kondor wielki", "B) Orzeł bielik", "C) Jastrząb zwyczajny", "D) Biała gołębica"], ["B"]], ["Zwierzęta"]]
p1_mitologia_grecka = [[["Który z podanych herosów w mitologii greckiej uchodzi za syna Zeusa?"],["A) Achilles","B) Jazon","C) Perseusz","D) Hippotoon"],["C"]], [["Która z podanych bogiń była opiekunką ogniska domowego?"], ["A) Atena", "B) Artemida", "C) Demeter", "D) Hestia"], ["D"]], [["Kim były Erynie?"], ["A) boginiami losu", "B) boginami zemsty", "C) bóstwami morskimi", "D) boginiami młodości"], ["B"]], ["Mitologia grecka"]]
p1_przysłowia = [[["Dokończ zdanie: a co po czyjej wielkości, jak nie ma w głowie…"],["A) radości","B) mądrości","C) ufności","D) miłości"],["B"]], [["Dokończ zdanie: czym skorupka za młodu nasiąknie, tym na starość…"], ["A) się stanie", "B) trąci", "C) będzie", "D) się okaże"], ["B"]], [["Uzupełnij: dobrego syna nigdy ___ nie zapomina: "], ["A) Bóg", "B) nikt", "C) się", "D) ojciec"], ["A"]], ["Przysłowia"]]
p1_święta = [[["W Polsce obchodzimy święto flagi:"],["A) 2 maja", "B) 3 maja", "C) 2 czerwca", "D) 3 czerwca"], ["A"]], [["Tradycyjną potrawą spożywaną z okazji Dnia Dziękczynienia jest:"],["A)pieczony indyk", "B) kurczak z rożna","C)bażant z pieca","D)kaczka po wietnamsku"], ["A"]], [["Polowanie na jajka to zwyczaj zwiazany z:"], ["A) Wielkanocą", "B) Bożym Narodzeniem", "C) Halloween", "D) Chanuką"], ["A"]], ["Święta"]]

# poziom drugi
p2_ogrodnictwo=[[["Nowalijki to warzywa, które ukazują się najczęściej: "],["A)późnym latem", "B)wczesną wiosną", "C)wczesną jesienią", "D)na przełomie wiosny i lata"], ["B"]], [["Gargamele, malinowe, bawole serca to popularne gatunki:"],["A) papryki", "B) ogórków", "C)pomidów", "D)cebuli"], ["C"]], [["Zimni ogrodnicy to okres, w którym występują majowe przymrozki; nazwa ta jest związana ze wspomnieniem świętych:"], ["A) Pawła, Piotra, Alojzego, Anny"], ["B) Pankracego, Serwacego, Bonifacego, Zofii"],["Walentego, Józefa, Danuty, Łukasza"], ["Agnieszki, Anastazego, Ildefonsa, Tymoteusza "]], ["B"]]
p2_sporty_ekstremalne= [[["tak zwany solo climbing to rodzaj sporu ekstremalnego, który polega na wspinaczce bez: "],["A) partnerów","B)partnerów oraz lin zabezpieczających","C) lin zabezpieczających","D) partnerów i jakiegokolwiek sprzętu ochronnego"],["D"]], [["W którym wieku Janina Mey jako pierwsza Polka wykonała skok ze spadochronem?"], ["A) XX w.", "B) XIX w", "C)  XVIII w.", "D)  XVI w."], ["B"]], [["Który z wymienionych sportów nie jest uznawany za sport ekstremalny?"],
["A)rower górski ", "B) wyścigi łodzi motorowych", "C) spacery na linie ", "D) kajakarstwo"], ["D"]], ["Sporty ekstremalne"]]
p2_muzyka_filmowa=[[["Kto jest autorem muzyki do filmu Christophera Nolana pod tytułem “Interstellar”?"],["A) Thomas Newman","B) Hans Zimmer","C) John Williams","D) James Horner"],["B"]], [["Za muzykę do którego filmu Ennio Morricone otrzymał Oscara w 2016 roku?"], ["A) “Pewnego Razu na Dzikim Zachodzie”", "B)“Nienawistna Ósemka”", "C)“Za garść dolarów”", "D) “Dawno Temu w Ameryce”"], ["B"]], [["W którym roku Howard Shore otrzymał Oscara za muzykę do “Władcy Pierścieni - Drużyny Pierścienia”?"], ["A)2003", "B) 2001", "C) 2002", "D)2004"], ["C"]], ["muzyka_filmowa"]]
p2_krolowie_polski: [[["Kto był pierwszym koronowanym królem Polski?"],["A) Bolesław Chrobry","B) Mieszko I","C) Bolesław Śmiały","D) Mieszko II"],["A"]], [["Który król Polski był mężem Królowej Jadwigi Andegaweńskiej?"], ["A) Mieszko I", "B)Bolesław Śmiały", "C) Bolesław Krzywousty", "D) Władysław Jagiełło "], ["D"]], [["Za rządów którego króla wydano przywilej koszycki?"], ["A) Ludwika Węgierskiego", "B) Władysława Jagiełły", "C) Stanisława Augusta Poniatowskiego", "D)Bolesława Krzywoustego"], ["B"]], ["Królowie Polski"]]

# poziom trzeci
p3_miasta_wojewodzkie=[[["Olsztyn jest miastem wojewódzkim którego województwa?"],["A)Warmińsko-mazurskiego","B)Kujawsko-pomorskiego","C)Zachodniopomorskiego","D) Podkarpackiego"],["A"]], [["Które miasto wojewódzkie liczy najwięcej ludności?"], ["A) Kraków", "B) Warszawa", "C) Poznań", "D) Bydgoszcz"], ["B"]], [["W którym mieście  wojewódzkim możemy oglądać Spodek?"], ["A)W Katowicach", "B) W Krakowie", "C) W Bydgoszczy", "D) W Poznaniu"], ["A"]], ["Miasta wojewódzkie"]]
p3_jedzenie=[[["silnie trująca ryba, będącą tradycyjnym japońskim przysmakiem to:"],["A) Fugu","B) Koi","C) Tara","D) Tsuna "],["A"]], [["Pizza hawajska pochodzi: "], ["A)  z Norwegii ", "B) z Francji", "C) z Kanady", "D) z Wielkiej Brytanii "], ["C"]], [["Co uznawane jest za najsłodszy owoc na świecie?"], ["A) mango", "B) granaty", "C) figi", "D) banan"], ["C"]], ["Jedzenie"]]
p3_zabytki=[[["Budowę katedry Notre Dame datuje się na:"],["A) XII-XIV wiek","B) XV-XVIII wiek","C) IX-XI wiek ","D) XVIII-XX wiek "],["A"]], [[" Tadź Mahal to: "], ["A) kościół", "B) zamek", "C) pałac", "D)mauzoleum"], ["D"]], [["Stonehenhe znajduje się w:"], ["A)Wielkiej Brytanii", "B)Stanach Zjednoczonych", "C)Chile", "D) Brazylii"], ["A"]], ["Zabytki"]]
p3_znane_strony_internetowe=[[["Biała, niekompletna kula ułożona z puzzli, to logo jakiej strony internetowej?"],["A) Twittera","B) Google","C) Wikipedii","D) Yahoo!"],["C"]], [["Wymień w poprawnej kolejności kolory znajdujące się na logo strony Google.com:"], ["A) Żółty, niebieski, czerwony, niebieski, zielony, żółty", "B) b) Niebieski, czerwony, żółty, niebieski, zielony, czerwony", "C)Czerwony, zielony, niebieski, czerwony, żółty, niebieski", "D) Zielony, żółty, czerwony, niebieski, czerwony niebieski"], ["B"]], [["W którym roku powstał portal społecznościowy Facebook?"], ["A) 2005", "B) 2006", "C) 2004", "D) 2003"], ["C"]], ["znane strony internetowe"]]

# poziom czwarty
p4_muzyka_klasyczna=[[["W jakim mieście pochowany jest Fryderyk Chopin?"],["A) W Paryżu","B) W Warszawie","C) W Wilnie ","D) W Krakowie "],["A"]], [[" Które z podanych dzieł skomponował Jan Sebastian Bach?"], ["A) Aria na strunie G", "B) Clair de Lune", "C) Lacrimosa", "D) Dies irae"], ["A"]], [["Kto jest autorem “Jeziora Łabędziego”?"], ["A)Pyotr Ilyich Tchaikovsky", "B)Wolfgang Amadeus Mozart", "C) Karl Ditters von Dittensdorf", "D) Franciszek Liszt"], ["A"]], ["Muzyka klasyczna"]]
p4_religie=[[["Wedy to święte księgi:"],["A) buddyzmu ","B)hinduizmu","C)islamu","D) judaizmu"],["B"]], [["Za początek islamu uznaje się:"], ["A) VII wiek n.e", "B)V wiek p.n.e", "C) VII wiek p.n.e", "D)V wiek n.e"], ["A"]], [["Na skutek wielkiej schizmy wschodniej: "], ["A)nastąpił podział Kościoła katolickiego ", "B)na tronie papieskim zasiadło trzech papieży jednocześnie ", "C)Wielka Brytania ustanowiła anglicyzm religię narodową ", "D) przeniesiono stolicę papieską z Paryża do Rzymu"], ["A"]], ["Religie i wierzenia"]]
p4_literatura=[[["Autorem powieści pt. “Lolita” uchodzącej za jedno z najbardziej kontrowersyjnych dzieł w historii jest: "],["A)  Michaił Bułhakow","B) Andriej Płatonow ","C) Vladimir Nabokov ","D)  Dmitrij Bykow"],["C"]], [["“Lalka” Bolesława Prusa to powieść:"], ["A)romantyczna ", "B) pozytywistyczna", "C) oświeceniowa", "D)z okresu XX-lecia międzywojennego"], ["B"]], [["Jaki tytuł nosi najważniejsze dzieło Andrzeja Frycza Modrzewskiego? "], ["A)Kazania sejmowe ", "B) Wojna chocimska", "C) O poprawie Rzeczypospolitej", "D) Rytmy albo wiersze polskie "], ["C"]], ["Literatura"]]
p4_komputery=[[["Która z wymienionych nazw nie jest nazwą języka programowania?"],["A) Python","B) Prolog","C) Braor","D) Nim"],["C"]], [["Który słynny uczony jest nazywany ojcem nowoczesnego systemu binarnego?"], ["A) Gottfried Leibniz", "B) Isaac Newton", "C) Noam Chomsky", "D) Marvin Minsky"], ["A"]], [["Kto jest uznawany za twórcę pierwszego programu komputerowego?"], ["A)Marvin Minsky", "B)Ada Lovelace", "C)Ludwig Wittgenstein", "D) Gottfried Leibniz"], ["B"]], ["Komputery"]]

# poziom piąty
p5_imiona_zenskie=[[["Które z tych imion jest jednocześnie nazwą języka programowania wykorzystywanym w kontroli lotów?"],["A) Ada","B)Martha","C) Sasha"],["A"]], [["Które z tych imion wywodzi się z języka greckiego?"], ["A) Julia", "B) Barbara", "C) Rebeka"], ["B"]], [["Jak nazywa się postać biblijna, która ucięła głowę wodzowi Asyryjczyków?"], ["A) Judyta", "B) Batszeba", "C) Rebeka"], ["A"]], ["Imiona żeńskie"]]
p5_alkohol=[[["Dochód ze sprzedaży jednego z najdroższych piw na świecie- Nail Brewing's Antarctic Nail Ale- przekazywany jest fundacji zajmującej się ochroną"],["A) niedźwiedzi polarnych","B) wielorybów","C) fok"],["B"]], [["Kiedy została wymyślona jedna z najpopularniejszych gier alkoholowych tzw. beer pong?"], ["A) lata 50 XX wieku", "B) lata 90 XX wieku ", "C) lata 20 XX wieku"], ["A"]], [["Jaki alkohol jest uważany za trunek handlarzy niewolników, oszustów i przemytników?"], ["A) whisky", "B) rum", "C) piwo"], ["B"]], ["Alkohol"]]
p5_geografia=[[["Honolulu jest stolicą:"],["A) Jamajki","B) Hawajów","C) Honolulu"],["B"]], [["Tadżykistan leży w:"], ["A) Afryce", "B) Azji", "C) Ameryce Południowej"], ["B"]], [["Najdłuższą rzeką świata jest Nil. Drugie miejsce zajmuje:"], ["A) Amazonka", "B) Jangcy", "C) Missisipi"], ["A"]], ["Geografia"]]
p5_komiksy=[[["Który z podanych bohaterów jest komiksowym dzieckiem rysownika Boba Kane'a?"],["A) Spider-Man","B) Batman","C) Superman"],["B"]], [["Superbohater DC Comics poruszający się z wielką prędkością to:"], ["A) Shazzam", "B) Flash", "C) Green Lantern"], ["B"]], [["Który z podanych bohaterów komiksów Marvela jest nazywany “Pierwszym Avengersem”?"], ["A) Iron Man", "B) Thor", "C) Kapitan Ameryka"], ["C"]], ["Komiksy"]]

# # poziom szósty
p6_nawiazania_religijne=[[["Po jakiej krainie spaceruje Jack, główny bohater filmu Larsa von Triera pod tytułem Dom, który zbudował Jack?"],["A) Po niebie","B) Po Edenie","C) Po piekle"],["C"]], [["Kim jest mężczyzna, partner tytułowej Matki, w filmie Darrena Aronofsky’ego pod tytułem “Mother!”?"], ["A)Poetą", "B) Bogiem", "C) Artystą"], ["B"]], [["Który z siedmiu grzechów głównych reprezentuje antagonista filmu pod tytułem “Se7en” w reżyserii Davida Finchera?"], ["A) Pychę", "B) Złość", "C) Zazdrość"], ["C"]], ["nawiązania religijne we współczesnej kinematografii"]]
p6_seriale=[[["W Polsce najchętniej oglądanym serialem Netflixa w 2019 roku był:"],["A) Dom z papieru ","B)Stranger Things","C) Wiedźmin"],["C"]], [["Cytat “Dzieci się zawsze źle komponują w mieszkaniu” pochodzi z:"], ["A) Czterdziestolatka", "B)Złotopolskich", "C)Świata według Kiepskich"], ["B"]],[["Który z tych seriali nakręcono najwcześniej?"]], ["A) Przyjaciele","B)Słoneczny patrol","C) Jak poznałem waszą matkę"], ["B"]], ["Seriale"]
p6_psychologia=[[["Prawo głoszące, że im więcej czasu mamy na wykonanie jakiejś pracy, tym więcej czasu nam ono zabiera, nazywamy:"],["A)Prawem Parkinsona","B) Prawem Morisona","C) Prawem Pareta"],["A"]], [["Tendencja do automatycznego, pozytywnego lub negatywnego, przypisywania cech na podstawie pierwszego wrażenia to: "], ["A)Efekt Rosenthala", "B)efekt halo", "C)Efekt Pollyanny"], ["B"]], [["Efekt coctail party polega na: "], ["A)uwrażliwieniu na wszelkie bodźce odnoszące się bezpośrednio do nas", "B) uwrażliwieniu na bodźce odnoszące się do środowiska, w którym się znajdujemy ", "C)dostosowywaniu naszego zachowania do zachowań powszechnych, społecznie akceptowalnych"], ["A"]], ["psychologia"]]
p6_wyspy=[[["Które z tych wysp wchodzą w skład terytorium Australii?"],["A) Wyspy Kokosowe","B) Wyspy Cooka","C)  Wyspy Wielkanocne"],["A"]], [["Do terytorium którego z tych państw nie zalicza się wyspa Borneo?"], ["A) Indonezja", "B) Brunei", "C) Papua-Nowa Gwinea"], ["C"]], [["Do terytorium jakiego państwa zalicza się Wyspa Wiktorii?"], ["A) Kanada", "B) Nowa Zelandia", "C)Wielka Brytania"], ["A"]], ["Wyspy"]]

# poziom siódmy
p7_polska_fantastyka = [[["Imię ukochanej Daimona Freya, bohatera “Siewcy Wiatru” autorstwa Mai Lidii Kossakowskiej?"],["A) Hija","B) Lilith","C) Drop"],["A"]], [["Imię czarodziejki z serii książek o Wiedźminie, autorstwa Andrzeja Sapkowskiego, która należała do Rady Królewskiej Temerii?"], ["A)Keira Metz", "B) Yennefer z Vengerbergu", "C)Fringilla Vigo"], ["A"]], [["Kim była obrończyni, którą otrzymał od klasztoru Amszilas inkwizytor Mordimer Madderdin, bohater serii książek Jacka Piekary?"], ["A) Inkwizytorką", "B) Zakonnicą", "C) Anielicą"], ["C"]], ["Polska fantastyka"]]
p7_waluty = [[["Waluta wenezuelska to: "],["A)dolar","B) somoni","C)boliwar "],["C"]], [["Państwem, w którym walutą nie jest peso, jest/są:"], ["A) Filipiny", "B) Dominikana ", "C) Bahamy"], ["C"]], [["1 peso meksykańskie to w przeliczeniu:"], ["A) 1,08 zł ", "B)0,18 zł ", "C) 0,46 zł "], ["B"]], ["waluty"]]
p7_gory = [[["Który łańcuch górski z podanych poniżej jest najmłodszy? "],["A)Sudety","B) Karpaty","C) Góry Świętokrzyskie"],["B"]], [["Jaki jest najwyższy szczyt Azerbejdżanu?"], ["A) Bazardüzü", "B) Hazrat Sulton", "C) Czogori"], ["A"]], [["Jaka jest średnia roczna temperatura na szczycie Śnieżki?"], ["A) 5 st. C", "B)0,4 st. C", "C) -4 st. C"], ["B"]], ["góry"]]
p7_kuchnie_swiata = [[["Włoska potrawa cotoletta alla milanese najbardziej przypomina..."],["A)Pierogi z kapustą i z grzybami","B) Placki ziemniaczane","C)Kotlet schabowy"],["C"]], [["Gazpacho to zupa, która zazwyczaj ma kolor…"], ["A) Czerwony", "B) Zielony", "C) Żółty"], ["A"]], [["Jedna z najpopularniejszych w Chinach zup jest robiona z jaskółczych…"], ["A) łap", "B)gniazd", "C) języków"], ["B"]], ["kuchnie świata"]]

# poziom ósmy
p8_uczeni= [[["Który z tych XVII-wiecznych uczonych urodził się wcześniej?"],["A)Gottfried Leibniz","B)Isaac Newton"],["B"]], [["W którym roku został ścięty Antoine Lavoisier, wybitny francuski chemik?"], ["A) W 1793", "B)W 1794"], ["B"]], [["W którym z tych włoskich miast urodził się Galileusz?"], ["A) Piza", "B)Mediolan"], ["A"]], ["uczeni wszechczasów"]]
p8_prl= [[["Ile mierzyła Warszawska Radiostacja Centralna w Gąbinie, która do 1991 roku była najwyższym obiektem wzniesionym przez człowieka? "],["A) ponad 646 metrów ","B)ponad 846 metrów "],["A"]], [["Pierwsze częściowo wolne wybory w historii Polski po II wojnie światowej  odbyły się w roku:"], ["A) W 1991 ", "B)W 1989 "], ["B"]], [["Co, według propagandy PRL, Amerykanie zrzucali z samolotów nad Polską? "], ["A) stronkę ziemniaczaną ", "B)odpady promieniotwórcze"], ["A"]], ["PRL"]]
p8_kosmos= [[["Ile księżyców ma Jowisz? "],["A) 79","B) 89"],["A"]], [["W którym roku odbył się pierwszy turystyczny lot w kosmos?"], ["A) W 2005", "B)W 2001"], ["B"]], [["Kiedy najszybciej będziemy mogli obserwować kometę Halleya? "], ["A) W 2050", "B)W 2061"], ["B"]], ["kosmos"]]
p8_gry_wideo= [[["Miejsce akcji dodatku do Bioshocka Infinite Burial at Sea?"],["A)Columbia","B)Rapture"],["B"]], [["Nazwa starszego smoka w grze Monster Hunter: World, którego główny atak polega na zabieraniu życia graczowi?"], ["A) Kushala Daora", "B)Vaal Hazak"], ["B"]], [["Imię postaci w grze Dota 2, demona, którego znamy pod przydomkiem Queen of Pain?"], ["A)Akasha", "B)Shendelzare"], ["A"]], ["gry wideo"]]
